# Generated by Django 3.0 on 2021-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_auto_20210707_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobilenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
